// api/describe-planet.js — planet-in-sign description generator for elsewhere
//
// Given a planet + sign, returns a short paragraph describing what that
// placement is and what its astrocartography lines amplify. Generated by
// Claude on first request, cached in Supabase so subsequent requests for
// the same placement return instantly and at zero ongoing cost.
//
// Architecture:
//   1. POST { planet, sign }  -> check cache
//   2. Cache hit  -> return cached paragraph
//   3. Cache miss -> generate via Claude, save to cache, return paragraph
//
// Cache key is "<planet>:<sign>" (lowercased). 10 planets x 12 signs = 120
// possible unique entries; once populated the API rarely touches Claude.

const Anthropic = require('@anthropic-ai/sdk').default || require('@anthropic-ai/sdk');
const { createClient } = require('@supabase/supabase-js');

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

// ── Validation ──────────────────────────────────────────────────
// Only accept known planet and sign names — guards against junk input
// polluting the cache and tightens the surface area of what we'll
// generate. Keep these lists exactly in sync with engine.js.
const VALID_PLANETS = [
  'Sun','Moon','Mercury','Venus','Mars','Jupiter','Saturn',
  'Uranus','Neptune','Pluto','Chiron','NNode'
];
const VALID_SIGNS = [
  'Aries','Taurus','Gemini','Cancer','Leo','Virgo',
  'Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'
];

// ── Voice anchors ───────────────────────────────────────────────
// These are the 12 hand-written paragraphs Sarah approved as the voice
// baseline. We pass them to Claude as examples so generated paragraphs
// match the same register: plain prose, honest about both gifts and
// costs, concrete behaviors over abstractions, no house-rulership
// language, ends by saying what the planet's lines amplify.
//
// Including all 12 in every prompt is a small token cost (~1.5k input
// tokens per call) but keeps voice consistency far better than a short
// instruction would. Since we cache aggressively, this cost is paid
// at most ~120 times total.
const VOICE_EXAMPLES = `
Example — Sun in Sagittarius:
Your Sun runs on motion, meaning, and the open road. You're built to chase what's bigger than you — ideas, philosophies, places, horizons — and identity comes through expansion, not through standing still. Strong placement, but Sagittarius has its tells: overcommitting to ideas you haven't fully thought through, restlessness when life gets too settled, promising more than you can deliver because the vision was bigger than the logistics. Sun lines pull you toward growth, travel, and the version of yourself that's still becoming — but expect the restlessness too, the urge to keep moving when you should be staying still.

Example — Moon in Aquarius:
The Moon in Aquarius needs space, oddness, and the freedom to belong on its own terms. Emotional safety comes through independence and chosen community more than through closeness or convention — but the cost is detachment from your own feelings when they get inconvenient. You can intellectualize what you're going through rather than feel it, and you may put friends at arm's length when they get too close. Moon lines bring access to your own emotional life — sometimes through the loneliness of being far from the familiar, sometimes through the unexpected weirdness of who you meet.

Example — Mercury in Sagittarius (a planet in detriment):
Mercury in Sagittarius thinks in big arcs, not fine print. You reach for meaning and the bigger picture, sometimes faster than the details can catch up — and in detriment here, that means missing what's actually being said, glossing over specifics, or stating things with more confidence than the evidence warrants. Combust by the Sun, your thinking also tends to blur into your sense of self, so it's hard to separate what you think from who you are. Mercury lines amplify the visions and the certainty — what you'll notice is louder conviction, bigger plans, and probably someone you should have listened to more carefully.

Example — Venus in Scorpio (a planet in detriment):
Venus in Scorpio loves with depth — but in detriment, it loves with a grip. You're drawn to intense relationships and you tend to stay in them past the point of healthiness; jealousy, possessiveness, the urge to merge so completely it stops being separate people. Surface-level rarely satisfies, which sounds romantic but in practice means you may turn small intimacies into power struggles. Venus lines turn relationships up — connections form fast, run deep, and may pull you back into patterns you've worked to leave behind.

Example — Mars in Leo:
Mars in Leo wants to be seen — performing, leading, taking up space. There's real charisma here, the kind that shifts a room. But the placement is famously dramatic: prone to ego flare-ups, taking things personally, outbursts when pride gets dented. Of-sect on a night chart, that fire runs hotter than it gives back — the strain shows up as temper, stubbornness, or a need to be right that overshoots the situation. Mars lines turn the volume up — more visible, more magnetic, but also more reactive; watch for fights you didn't mean to start.

Example — Jupiter in Scorpio (a planet in its own sign):
This is one of the strongest placements in your chart. Jupiter in its own sign and angular at the IC means real abundance — but Scorpio's flavor of abundance is depth, not breadth: wealth through inheritance, intimacy, shared resources, or what others bring you. Opportunity often arrives through endings, transformations, or the hidden being made visible. Out-of-sect, the gifts aren't loud — they accumulate quietly through what gets stripped away. Jupiter lines are among the strongest signals you have for opportunity; expect openings around money, depth, and people who change you.

Example — Saturn in Pisces:
Saturn in Pisces works through softening rather than hardening — the lessons come through letting go of structures rather than building them, which sounds gentle but often shows up as confusion, drift, or commitments you can't quite get out of. Out-of-sect, Saturn's weight lands harder than it gives back; what's asked of you tends to be more than the immediate reward. In the 7th, this plays out through partners — relationships that age you, contracts that bind, marriages that become work. Saturn lines bring the commitments and the weight of them — the people who shape who you become through how much they ask.

Example — Uranus in Capricorn (an outer / generational planet):
Uranus in Capricorn questions structures of authority — your generation came in to disrupt institutions, hierarchies, and the inherited order. In the 5th, this rebellion plays out through creativity, romance, and how you express yourself: an aversion to traditional ways of dating, of making art, of being a parent. Uranus lines bring sudden change to whatever's been routine — abrupt freedom, an unexpected creative breakthrough, or a romance that arrives sideways and rewrites your assumptions.

Example — Pluto in Scorpio (an outer planet in its modern rulership):
Pluto in Scorpio in the 4th is a heavyweight placement — Pluto in its own sign, angular, running through your roots. Transformation works through home, ancestry, family, the deepest parts of your private life. This is the generation that came in to dig up what was hidden: family secrets, generational patterns, what was buried. Pluto lines bring deep change, sometimes by choice, often not — what's outgrown gets stripped away whether you're ready or not, and what's been hidden in your private life tends to surface.

Example — Chiron in Virgo (a point with no rulerships):
Chiron in Virgo sits in the sign of analysis, service, and the body — and the wound tends to involve never feeling adequate, useful enough, or "right." Perfectionism, over-criticism of yourself, struggling to feel okay in your own body. In the 2nd, this often shows up around self-worth and money: the sense that you have to earn your value, never just have it. Chiron lines bring the wound closer to the surface — old patterns of self-criticism resurface, but so does the chance to meet them with less judgment than you have before.
`.trim();

function buildPrompt(planet, sign) {
  return `You write short astrological paragraphs for an astrocartography report. The user is reading about the planet ${planet} in their natal sign ${sign}, deciding where on Earth to spend time.

Write ONE paragraph (3-4 sentences, 80-130 words) describing ${planet} in ${sign}, in the same voice as the examples below. The paragraph should:

- Describe the placement in concrete, lived-experience terms — what it actually looks and feels like in someone's behavior, not abstract symbolism.
- Be honest about both gifts AND costs. Don't flatter difficult placements; don't hedge the bright spots.
- Mention specific patterns or behaviors a person might recognize in themselves.
- NEVER reference house rulerships ("rules your Nth house") — house position changes with location in astrocartography, so it's misleading.
- End by saying what the planet's lines amplify, in one short clause — what the person will encounter or notice when standing near them.
- Stay in plain English; minimal astrology jargon. No "natives," no "this placement bestows," no overly mystical phrasing.

${VOICE_EXAMPLES}

Now write the paragraph for ${planet} in ${sign}. Output only the paragraph itself — no preamble, no heading, no "Here is the paragraph". Just the prose.`;
}

// ── Fallback paragraph for when both cache and Claude fail ──────
// Better to show a generic-but-on-voice line than to break the page.
function fallbackParagraph(planet, sign) {
  return `${planet} in ${sign} colors how this planet shows up in your life. ${planet} lines bring that energy more strongly to the surface wherever you stand near them.`;
}

// ── The endpoint ────────────────────────────────────────────────
module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // ── Parse + validate input ────────────────────────────────────
  const { planet, sign } = req.body || {};
  if (!planet || !sign) {
    return res.status(400).json({ error: 'planet and sign are required' });
  }
  if (!VALID_PLANETS.includes(planet)) {
    return res.status(400).json({ error: `Invalid planet: ${planet}` });
  }
  if (!VALID_SIGNS.includes(sign)) {
    return res.status(400).json({ error: `Invalid sign: ${sign}` });
  }

  // Display-friendly planet name. Used only in prompts; the cache key
  // still uses the internal canonical name.
  const promptPlanet = planet === 'NNode' ? 'North Node' : planet;
  const cacheKey = `planet_sign:${planet.toLowerCase()}:${sign.toLowerCase()}`;

  // ── Step 1: try cache ─────────────────────────────────────────
  try {
    const { data: cached, error: cacheErr } = await supabase
      .from('description_cache')
      .select('content')
      .eq('cache_key', cacheKey)
      .maybeSingle();

    if (cacheErr) {
      // Log but don't fail — we'll fall through to generation.
      console.error('Cache lookup error:', cacheErr.message);
    }
    if (cached && cached.content) {
      return res.status(200).json({
        planet,
        sign,
        paragraph: cached.content,
        source: 'cache'
      });
    }
  } catch (ex) {
    console.error('Cache layer crashed:', ex.message);
    // Continue to Claude — caching is an optimization, not a hard
    // requirement for the endpoint to work.
  }

  // ── Step 2: cache miss, generate via Claude ───────────────────
  let paragraph;
  try {
    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 400,   // ~300 words, plenty for a 3-4 sentence paragraph
      messages: [{
        role: 'user',
        content: buildPrompt(promptPlanet, sign)
      }]
    });
    paragraph = response.content[0].text.trim();
  } catch (ex) {
    console.error('Claude generation failed:', ex.message);
    return res.status(200).json({
      planet,
      sign,
      paragraph: fallbackParagraph(promptPlanet, sign),
      source: 'fallback',
      error: ex.message
    });
  }

  // ── Step 3: save to cache (best-effort, don't block response) ─
  // If the insert fails (race condition, downtime, RLS misconfig)
  // we still return the freshly generated paragraph — the user
  // doesn't care; future requests will retry caching.
  try {
    const { error: insertErr } = await supabase
      .from('description_cache')
      .insert({ cache_key: cacheKey, content: paragraph });
    if (insertErr) {
      // Likely a duplicate key from a race condition — that's fine.
      console.warn('Cache insert error:', insertErr.message);
    }
  } catch (ex) {
    console.warn('Cache insert crashed:', ex.message);
  }

  return res.status(200).json({
    planet,
    sign,
    paragraph,
    source: 'generated'
  });
}
