// api/describe-aspect.js — aspect explanation generator for elsewhere
//
// Given two planets + an aspect type, returns a short paragraph describing
// what that aspect means in a person's life. Generated by Claude on first
// request, cached in Supabase so subsequent requests for the same aspect
// return instantly and at zero ongoing cost.
//
// Mirrors api/describe-planet.js exactly in structure: same cache table,
// same generate-on-miss-then-cache flow, same fallback safety.
//
// Architecture:
//   1. POST { planet1, planet2, aspect }  -> build canonical key
//   2. Cache hit  -> return cached paragraph
//   3. Cache miss -> generate via Claude, save to cache, return paragraph
//
// IMPORTANT — canonical key:
//   Aspects are bidirectional: "Mars square Pluto" and "Pluto square Mars"
//   are the SAME aspect. To avoid generating/storing two paragraphs for one
//   relationship, the two planet names are sorted alphabetically before the
//   key is built. Both orders therefore produce:
//        aspect:mars:pluto:square
//   The DISPLAY label on the card (e.g. "Mars square Pluto", leading with
//   the card's planet) is built separately in report.html — storage order
//   and display order are independent by design.
//
// Aspect copy is intentionally SIGN-AGNOSTIC. The sign and condition story
// (e.g. "Mercury in Sagittarius, detriment, combust") is carried by the
// planet-in-sign paragraph above the aspect note on the card. Keeping the
// aspect universal is what lets it cache once per pair and serve forever.

import Anthropic from '@anthropic-ai/sdk';
import { createClient } from '@supabase/supabase-js';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

// ── Validation ──────────────────────────────────────────────────
// Reuse the same planet list as describe-planet.js — keep in sync with
// engine.js. Aspect types are the five major (Ptolemaic) aspects only,
// matching the engine's ASPECT_BASE table.
const VALID_PLANETS = [
  'Sun','Moon','Mercury','Venus','Mars','Jupiter','Saturn',
  'Uranus','Neptune','Pluto','Chiron','NNode'
];
const VALID_ASPECTS = [
  'conjunction','sextile','square','trine','opposition'
];

// ── Voice anchors ───────────────────────────────────────────────
// Hand-written, Sarah-approved aspect paragraphs that set the voice for
// all generated copy. Same register as the planet-in-sign anchors: plain
// prose, honest about both gift and cost, concrete lived patterns, no
// house-rulership language. Two extra things these teach that the planet
// anchors can't:
//   1. Hard aspects (square/opposition) name the friction honestly; soft
//      aspects (trine/sextile) name the gift without overselling.
//   2. Conjunctions are NOT one flavor — their weight depends on the
//      planets. The examples deliberately range from significant
//      (Jupiter-Pluto) to everyday (Sun-Mercury) to generational and
//      downplayed (Uranus-Neptune), so generated outer-planet aspects
//      read as background cohort signatures, not personal drama.
const VOICE_EXAMPLES = `
Example — Mars square Pluto (a hard aspect between two heavy planets):
A square between Mars and Pluto is raw power under pressure. You don't do anything halfway — drive, will, and the urge to push past resistance run hot, but the same force that gets things done can tip into control, intensity, or a fight you can't let go of. The pattern to watch is the standoff that didn't need to be one. Where these two pull on each other, action carries weight, and what you push against tends to push back.

Example — Venus trine Saturn (a supportive aspect):
Venus trine Saturn is love that knows how to last. There's a steadiness to how you bond — loyalty, patience, a preference for what's real over what's merely exciting — and commitment tends to feel like relief rather than a cage. The cost is mild: warmth can run cooler than you mean it to, and you may make people earn their way in slowly. But this is one of the quietly reliable threads in your chart; it gives your closeness a backbone.

Example — Mars square Jupiter (a hard aspect, malefic to benefic):
Mars square Jupiter is the engine that overshoots. Confidence and drive feed each other here, which can mean bold, generous, go-big energy — but also overreach: promising more than the day allows, acting on a plan before it's fully cooked, mistaking enthusiasm for readiness. The friction shows up as the commitment that was bigger than the follow-through. The gift is real momentum; the work is aiming it before you fire.

Example — Jupiter conjunction Pluto (a conjunction — benefic fused with a heavy planet, significant):
Jupiter conjunct Pluto fuses growth with intensity — when you want something, you want it completely, and you have a knack for transformation on a large scale. It can bring real power and the ability to rebuild from the ground up. But the same fusion can turn belief into obsession, or the pursuit of more into a need to control the outcome. Where these meet, your reach deepens, and the things you chase tend to change you.

Example — Sun conjunction Mercury (a conjunction — neutral, the everyday kind):
Sun conjunct Mercury means your mind and your identity sit close together — you think the way you are, and you tend to speak in the first person even about ideas. It sharpens focus and makes your thinking feel personal and direct. The flip side is a blind spot: it can be hard to tell your opinions from objective fact, or to step outside your own viewpoint. Mostly this just makes you articulate about exactly the things that matter to you.

Example — Uranus conjunction Neptune (a conjunction — two outer/generational planets, downplayed):
This is a generational signature more than a personal one — Uranus and Neptune met in the sky for everyone born around your time, marking a cohort that came in to dissolve old structures and dream up new ones. In a single chart it works quietly, a background hum of restlessness and idealism rather than a loud personal trait. Where it touches your lines, expect a faint pull toward the unconventional and the visionary.
`.trim();

// Human-friendly description of each aspect's basic nature, fed into the
// prompt so Claude frames the relationship correctly.
const ASPECT_NATURE = {
  conjunction: 'a conjunction (the two planets fused together; whether this is easy or hard depends on the planets involved)',
  sextile:     'a sextile (a supportive, opportunity-flavored aspect — gentler than a trine)',
  square:      'a square (a hard, friction-filled aspect — tension that demands action)',
  trine:       'a trine (a flowing, supportive aspect — talent that comes easily)',
  opposition:  'an opposition (a polarizing aspect — a push-pull between two ends)'
};

function buildPrompt(p1, p2, aspect) {
  const nature = ASPECT_NATURE[aspect];
  return `You write short astrological paragraphs for an astrocartography report. The user is reading about an aspect in their natal chart: ${p1} ${aspect} ${p2}. This is ${nature}.

Write ONE paragraph (2-3 sentences, 50-75 words) describing what ${p1} ${aspect} ${p2} means in a person's life, in the same voice as the examples below. The paragraph should:

- Describe the aspect in concrete, lived-experience terms — what the relationship between these two planets actually looks and feels like in someone's behavior.
- Be honest about both gift AND cost. For hard aspects (square, opposition) name the friction plainly. For soft aspects (trine, sextile) name the gift without overselling, and note the mild cost.
- For a conjunction, judge its weight by the planets: benefic-heavy conjunctions are significant and warm; everyday pairings (like Sun-Mercury) are matter-of-fact; conjunctions between two outer/generational planets (Uranus, Neptune, Pluto) should be DOWNPLAYED as a cohort signature, not personal drama.
- NEVER reference signs, houses, or house rulerships. The aspect copy is universal — it must read true for anyone who has this aspect, regardless of where the planets sit. The sign-specific story is told elsewhere in the report.
- End with a short clause about what happens where these planets meet or near the person's lines.
- Stay in plain English; minimal jargon. No "natives," no "bestows," no overly mystical phrasing.

${VOICE_EXAMPLES}

Now write the paragraph for ${p1} ${aspect} ${p2}. Output only the paragraph itself — no preamble, no heading. Just the prose.`;
}

// ── Fallback paragraph for when both cache and Claude fail ──────
function fallbackParagraph(p1, p2, aspect) {
  return `${p1} ${aspect} ${p2} links these two parts of your chart, so they tend to show up together in your life. Where their lines meet, that connection becomes more pronounced.`;
}

// ── The endpoint ────────────────────────────────────────────────
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // ── Parse + validate input ────────────────────────────────────
  const { planet1, planet2, aspect } = req.body || {};
  if (!planet1 || !planet2 || !aspect) {
    return res.status(400).json({ error: 'planet1, planet2 and aspect are required' });
  }
  if (!VALID_PLANETS.includes(planet1)) {
    return res.status(400).json({ error: `Invalid planet: ${planet1}` });
  }
  if (!VALID_PLANETS.includes(planet2)) {
    return res.status(400).json({ error: `Invalid planet: ${planet2}` });
  }
  if (!VALID_ASPECTS.includes(aspect)) {
    return res.status(400).json({ error: `Invalid aspect: ${aspect}` });
  }
  if (planet1 === planet2) {
    return res.status(400).json({ error: 'planet1 and planet2 must differ' });
  }

  // ── Canonical key: sort planets alphabetically so order doesn't
  //    matter. Both "Mars square Pluto" and "Pluto square Mars" key to
  //    aspect:mars:pluto:square and share one cached paragraph. ───────
  const pair = [planet1, planet2].sort(); // alphabetical
  const lo = pair[0];
  const hi = pair[1];
  const cacheKey = `aspect:${lo.toLowerCase()}:${hi.toLowerCase()}:${aspect.toLowerCase()}`;

  // Display names for the prompt (NNode -> North Node). We feed the
  // alphabetical order to Claude too — the copy is symmetric, so order
  // in the prose doesn't matter, and keeping it tied to the canonical
  // order means the cached text always matches the cached key.
  const promptP1 = lo === 'NNode' ? 'North Node' : lo;
  const promptP2 = hi === 'NNode' ? 'North Node' : hi;

  // ── Step 1: try cache ─────────────────────────────────────────
  try {
    const { data: cached, error: cacheErr } = await supabase
      .from('description_cache')
      .select('content')
      .eq('cache_key', cacheKey)
      .maybeSingle();

    if (cacheErr) {
      console.error('Cache lookup error:', cacheErr.message);
    }
    if (cached && cached.content) {
      return res.status(200).json({
        planet1, planet2, aspect,
        paragraph: cached.content,
        source: 'cache'
      });
    }
  } catch (ex) {
    console.error('Cache layer crashed:', ex.message);
  }

  // ── Step 2: cache miss, generate via Claude ───────────────────
  let paragraph;
  try {
    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 400,
      messages: [{
        role: 'user',
        content: buildPrompt(promptP1, promptP2, aspect)
      }]
    });
    paragraph = response.content[0].text.trim();
  } catch (ex) {
    console.error('Claude generation failed:', ex.message);
    return res.status(200).json({
      planet1, planet2, aspect,
      paragraph: fallbackParagraph(promptP1, promptP2, aspect),
      source: 'fallback',
      error: ex.message
    });
  }

  // ── Step 3: save to cache (best-effort) ───────────────────────
  try {
    const { error: insertErr } = await supabase
      .from('description_cache')
      .insert({ cache_key: cacheKey, content: paragraph });
    if (insertErr) {
      console.warn('Cache insert error:', insertErr.message);
    }
  } catch (ex) {
    console.warn('Cache insert crashed:', ex.message);
  }

  return res.status(200).json({
    planet1, planet2, aspect,
    paragraph,
    source: 'generated'
  });
}
